# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.6.2
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  # Prevent issues like the following happening:
  # https://github.com/sickill/rainbow/issues/44
  - gem update --system
  # NOTE: bundler-audit is pegged to Bunder ~> 1.2, so this app cannot
  # currently be upgraded to use Bundler ~> 2.0
  - gem install bundler -v 1.17.3
script:
  # Ensure gem dependencies do not have known vulnerabilities
  - bin/bundle-audit check --update
  # Ensure each dependency has a permissive license
  - bin/license_finder
  # Run tests
  - bin/rake test
  # Run reek code quality check
  - bin/reek
  # Run Rubocop code quality check
  - bin/rubocop --display-cop-names
after_script:
  # Send results to Code Climate
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
