# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.2
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
  # Prevent issues like the following happening:
  # https://github.com/sickill/rainbow/issues/44
  - gem update --system
  - gem install bundler -v 1.16.0
script:
  # Ensure gem dependencies do not have known vulnerabilities
  - bin/bundle-audit check --update
  # Ensure each dependency has a permissive license
  - bin/license_finder
  # Run tests
  - bin/rake test
  # Run reek code quality check
  - bin/reek
  # Run Rubocop code quality check
  - bin/rubocop --display-cop-names
after_success:
  # Send results off to Code Climate
  - bin/codeclimate-test-reporter
